# Site settings
title: Como Programar - Hablar es barato, Enséñame el código
email: kedinn.th@gmail.com
author: kedinn
description: "Cómo aprender a programar en Android y Java, C# (Sharp), C++, html, PHP, Visual Basic, Javascript, Objetive C, Juegos, Python, Python,Hacking, 2015."
baseurl: /
url: "/"
twitter_username: kedinn2
github_username:  kedinn2
googleplus_username:  cprogramar
linkedinn_username:  cprogramar
youtube_username:  cprogramar
img-default: assets/default-cover.png

permalink: /:title
gems: [jekyll-paginate]
paginate: 8
paginate_path: "pagina:num"


exclude: ['Gemfile', 'Gemfile.lock', 'Capfile', 'config', 'lib', 'REVISION']

markdown: redcarpet
highlighter: true

redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

port: 4023

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets
    - _assets/javascript
    - _assets/stylesheets
    - _assets/images
    - _assets/images/wp
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false


